permalink: /:title

title: Setup Notes
url: https://gozoinks.github.io/
highlighter: none
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"